### PR TITLE
Fixed paths to work for Mac and Windows

### PR DESCRIPTION
**Pull request by wsyms**

### CODE REVIEW

**Comment by rmariuzzo** [comment]
Interesting @wsyms. I haven't tested on Windows as my main laptop is OSX. Did you had issues on Windows?

**Comment by wsyms** [comment]
@rmariuzzo Yes one of my co-workers is on Windows so the filesystem is different and we had to use `\` instead of `/` but we didn't want different webpack configurations

**Comment by rmariuzzo** [comment]
Great, thanks for the details. I will merge and publish a new version shortly.

**Comment by rmariuzzo** [comment]
@wsyms just to keep you in the loop. I have release a new version including your changes (v1.0.5). Thank you!

**Pull request merged**
